USE Microseguros
GO

CREATE TABLE Brands(
id INT NOT NULL,
name NVARCHAR(100) NOT NULL,
CONSTRAINT PK_B_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Devices(
id INT NOT NULL,
name NVARCHAR(100) NOT NULL,
CONSTRAINT PK_D_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Models(
id INT NOT NULL,
name NVARCHAR(100) NOT NULL,
brandId INT,
DeviceId INT,
quoted DECIMAL,
CONSTRAINT PK_M_ID PRIMARY KEY CLUSTERED (Id),
CONSTRAINT FK_BRANDID FOREIGN KEY (brandId) REFERENCES Brands(id),
CONSTRAINT FK_DEVICEID FOREIGN KEY (DeviceId) REFERENCES Devices(id)
)
GO

