CREATE DATABASE Microseguros
GO
USE Microseguros
GO
CREATE TABLE Documents(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_DOCUMENTS_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Cards(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_CARDS_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Users(
    id IDENTITY(1,1) NOT NULL,
    email NVARCHAR(100) NOT NULL,
    fullName NVARCHAR(100) NULL,
    docId INT NULL,
    docNumber INT NULL,
    CONSTRAINT PK_USERS_ID PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_USERS_DOCID FOREIGN KEY (docId) REFERENCES Documents(id)
)
Go
CREATE TABLE Ends(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_ENDS_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Brands(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_BRANDS_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Devices(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    icon nvarchar(MAX) NULL,
    CONSTRAINT PK_DEVICES_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Models(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    brandId INT,
    deviceId INT,
    -- quoted DECIMAL,
    CONSTRAINT PK_MODELS_ID PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_BRANDID FOREIGN KEY (brandId) REFERENCES Brands(id),
    CONSTRAINT FK_DEVICEID FOREIGN KEY (DeviceId) REFERENCES Devices(id)
)
GO

CREATE TABLE Addresses(
    id IDENTITY(1,1) NOT NULL,
    userId INT NOT NULL,
    postalCode NVARCHAR(6) NOT NULL,
    [location] nvarchar(50) NOT NULL,
    fullStreet nvarchar(150) NOT NULL,
    CONSTRAINT PK_ADDRESSES_ID PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_ADDRESSES_USERID FOREIGN KEY (userId) REFERENCES Users(id)
)
GO

CREATE TABLE CreditCards(
    id IDENTITY(1,1) NOT NULL,
    userId INT NOT NULL,
    [cardId] INT NOT NULL,
    [month] INT NOT NULL,
    code NVARCHAR(6) NOT NULL,
    fullName nvarchar(100) NOT NULL,
    CONSTRAINT PK_CREDITCARDS_ID PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_CREDITCARDS_USERID FOREIGN KEY (userId) REFERENCES Users(id),
    CONSTRAINT FK_CREDITCARDS_CARDID FOREIGN KEY (cardId) REFERENCES Cards(id)
)
GO
