CREATE DATABASE Microseguros
GO
USE Microseguros
GO

/*MASTER TABLES*/
CREATE TABLE Documents(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_DOCUMENTS_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Cards(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_CARDS_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Ends(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_ENDS_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Brands(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_BRANDS_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Devices(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    icon nvarchar(MAX) NULL,
    CONSTRAINT PK_DEVICES_ID PRIMARY KEY CLUSTERED (Id)  
)
GO
CREATE TABLE Models(
    id INT NOT NULL,
    name NVARCHAR(100) NOT NULL,
    brandId INT,
    deviceId INT,
    CONSTRAINT PK_MODELS_ID PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_BRANDID FOREIGN KEY (brandId) REFERENCES Brands(id),
    CONSTRAINT FK_DEVICEID FOREIGN KEY (DeviceId) REFERENCES Devices(id)
)
GO
CREATE TABLE ModelEnds(
    modelId INT NOT NULL,
    endId INT NOT NULL,
    quoted DECIMAL NOT NULL,
    insuredValue DECIMAL NOT NULL,
    CONSTRAINT PK_MODELENDS_ID PRIMARY KEY CLUSTERED (modelId, endId),
    CONSTRAINT FK_MODELENDS_MODELID FOREIGN KEY (modelId) REFERENCES Models(id),
    CONSTRAINT FK_MODELENDS_ENDID FOREIGN KEY (endId) REFERENCES Ends(id)
)
GO



/*OTHER TABLES*/
CREATE TABLE Users(
    id INT IDENTITY(1,1) NOT NULL,
    email NVARCHAR(100) NOT NULL,
    fullName NVARCHAR(100) NULL,
    docId INT NULL,
    docNumber INT NULL,
    CONSTRAINT PK_USERS_ID PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_USERS_DOCID FOREIGN KEY (docId) REFERENCES Documents(id)
)
Go

CREATE TABLE Addresses(
    id INT IDENTITY(1,1) NOT NULL,
    userId INT NOT NULL,
    postalCode NVARCHAR(6) NOT NULL,
    [location] nvarchar(50) NOT NULL,
    fullStreet nvarchar(150) NOT NULL,
    CONSTRAINT PK_ADDRESSES_ID PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_ADDRESSES_USERID FOREIGN KEY (userId) REFERENCES Users(id)
)
GO

CREATE TABLE CreditCards(
    id INT IDENTITY(1,1) NOT NULL,
    userId INT NOT NULL,
    [cardId] INT NOT NULL,
    [month] INT NOT NULL,
    code NVARCHAR(6) NOT NULL,
    fullName nvarchar(100) NOT NULL,
    CONSTRAINT PK_CREDITCARDS_ID PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_CREDITCARDS_USERID FOREIGN KEY (userId) REFERENCES Users(id),
    CONSTRAINT FK_CREDITCARDS_CARDID FOREIGN KEY (cardId) REFERENCES Cards(id)
)
GO

CREATE TABLE UserModels(
    userId INT NOT NULL,
    modelId INT NOT NULL,
    [state] INT NOT NULL,
    rate DECIMAL NOT NULL,
    CONSTRAINT PK_USERMODELS_ID PRIMARY KEY CLUSTERED (userId, modelId),
    CONSTRAINT FK_USERMODELS_USERID FOREIGN KEY (userId) REFERENCES Users(id),
    CONSTRAINT FK_USERMODELS_MODELID FOREIGN KEY (modelId) REFERENCES Models(id)
)
GO
CREATE TABLE Policies(
    id INT IDENTITY(1,1) NOT NULL,
    userId INT NOT NULL,
    modelId INT NOT NULL,
    endId INT NOT NULL,
    creditCardId INT NOT NULL,
    fromDate DATETIME NOT NULL,
    toDate DATETIME NULL,
    CONSTRAINT PK_POLICIES_ID PRIMARY KEY CLUSTERED (id),
    CONSTRAINT FK_POLICIES_USERID FOREIGN KEY (userId) REFERENCES Users(id),
    CONSTRAINT FK_POLICIES_MODELID FOREIGN KEY (modelId) REFERENCES Models(id),
    CONSTRAINT FK_POLICIES_ENDID FOREIGN KEY (endId) REFERENCES Ends(id),
    CONSTRAINT FK_POLICIES_CREDITCARDID FOREIGN KEY (creditCardId) REFERENCES CreditCards(id)
)
GO
CREATE TABLE [Log] (
   [Id] INT IDENTITY(1,1) NOT NULL,
   [Message] nvarchar(max) NULL,
   [MessageTemplate] nvarchar(max) NULL,
   [Level] nvarchar(128) NULL,
   [TimeStamp] datetimeoffset(7) NOT NULL,  
   [Exception] nvarchar(max) NULL,
   [Properties] xml NULL,
   [LogEvent] nvarchar(max) NULL
   CONSTRAINT [PK_LOG_ID] PRIMARY KEY CLUSTERED ([Id] ASC)
)
